# Generated by Django 5.1.5 on 2025-01-30 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraURLTable',
            fields=[
                ('extra_url_link', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extra_url_table',
            },
        ),
        migrations.CreateModel(
            name='URLTable',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'url_table',
            },
        ),
        migrations.CreateModel(
            name='PerformanceLighthouseTable',
            fields=[
                ('extra_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='performance', serialize=False, to='core.extraurltable')),
                ('performance_lighthouse', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'performance_lighthouse_table',
            },
        ),
        migrations.CreateModel(
            name='ResponsiveTable',
            fields=[
                ('extra_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsive', serialize=False, to='core.extraurltable')),
                ('tablet', models.BooleanField(default=False)),
                ('fold_phone', models.BooleanField(default=False)),
                ('normal_phone', models.BooleanField(default=False)),
                ('desktop', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'responsive_table',
            },
        ),
        migrations.CreateModel(
            name='StressTable',
            fields=[
                ('extra_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stress', serialize=False, to='core.extraurltable')),
                ('stress_check', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stress_table',
            },
        ),
        migrations.CreateModel(
            name='TestBreakTable',
            fields=[
                ('extra_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='test_break', serialize=False, to='core.extraurltable')),
                ('test_to_break', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test_break_table',
            },
        ),
        migrations.AddField(
            model_name='extraurltable',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_urls', to='core.urltable'),
        ),
    ]
