version: '1.0'

services:
  web:
    
    build: .
    ports:
      - "8000:8000"

    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    
    depends_on:
      - selenium
  
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: '2g'
    environment:
      - SE_NODE_MAX_SESSIONS=40
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true